// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shoppinglist.proto

package fi.mabrosim.shoppinglist.protobuf;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PbItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.PbItem)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string quantity = 3;</code>
     */
    java.lang.String getQuantity();
    /**
     * <code>string quantity = 3;</code>
     */
    com.google.protobuf.ByteString
        getQuantityBytes();

    /**
     * <pre>
     * array of checked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 checked = 4;</code>
     */
    java.util.List<java.lang.Long> getCheckedList();
    /**
     * <pre>
     * array of checked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 checked = 4;</code>
     */
    int getCheckedCount();
    /**
     * <pre>
     * array of checked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 checked = 4;</code>
     */
    long getChecked(int index);

    /**
     * <pre>
     * array of unchecked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 unchecked = 5;</code>
     */
    java.util.List<java.lang.Long> getUncheckedList();
    /**
     * <pre>
     * array of unchecked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 unchecked = 5;</code>
     */
    int getUncheckedCount();
    /**
     * <pre>
     * array of unchecked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 unchecked = 5;</code>
     */
    long getUnchecked(int index);

    /**
     * <code>bool is_checked = 6;</code>
     */
    boolean getIsChecked();

    /**
     * <pre>
     * timestamp in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>int64 checked_time = 8;</code>
     */
    long getCheckedTime();

    /**
     * <pre>
     * timestamp in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>int64 unchecked_time = 9;</code>
     */
    long getUncheckedTime();
  }
  /**
   * Protobuf type {@code protobuf.PbItem}
   */
  public  static final class PbItem extends
      com.google.protobuf.GeneratedMessageLite<
          PbItem, PbItem.Builder> implements
      // @@protoc_insertion_point(message_implements:protobuf.PbItem)
      PbItemOrBuilder {
    private PbItem() {
      name_ = "";
      quantity_ = "";
      checked_ = emptyLongList();
      unchecked_ = emptyLongList();
    }
    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    private void setId(long value) {
      
      id_ = value;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    private void clearId() {
      
      id_ = 0L;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.String name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 2;</code>
     */
    private void setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
    }
    /**
     * <code>string name = 2;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 2;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value.toStringUtf8();
    }

    public static final int QUANTITY_FIELD_NUMBER = 3;
    private java.lang.String quantity_;
    /**
     * <code>string quantity = 3;</code>
     */
    public java.lang.String getQuantity() {
      return quantity_;
    }
    /**
     * <code>string quantity = 3;</code>
     */
    public com.google.protobuf.ByteString
        getQuantityBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(quantity_);
    }
    /**
     * <code>string quantity = 3;</code>
     */
    private void setQuantity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      quantity_ = value;
    }
    /**
     * <code>string quantity = 3;</code>
     */
    private void clearQuantity() {
      
      quantity_ = getDefaultInstance().getQuantity();
    }
    /**
     * <code>string quantity = 3;</code>
     */
    private void setQuantityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      quantity_ = value.toStringUtf8();
    }

    public static final int CHECKED_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.LongList checked_;
    /**
     * <pre>
     * array of checked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 checked = 4;</code>
     */
    public java.util.List<java.lang.Long>
        getCheckedList() {
      return checked_;
    }
    /**
     * <pre>
     * array of checked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 checked = 4;</code>
     */
    public int getCheckedCount() {
      return checked_.size();
    }
    /**
     * <pre>
     * array of checked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 checked = 4;</code>
     */
    public long getChecked(int index) {
      return checked_.getLong(index);
    }
    private void ensureCheckedIsMutable() {
      if (!checked_.isModifiable()) {
        checked_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(checked_);
       }
    }
    /**
     * <pre>
     * array of checked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 checked = 4;</code>
     */
    private void setChecked(
        int index, long value) {
      ensureCheckedIsMutable();
      checked_.setLong(index, value);
    }
    /**
     * <pre>
     * array of checked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 checked = 4;</code>
     */
    private void addChecked(long value) {
      ensureCheckedIsMutable();
      checked_.addLong(value);
    }
    /**
     * <pre>
     * array of checked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 checked = 4;</code>
     */
    private void addAllChecked(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureCheckedIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, checked_);
    }
    /**
     * <pre>
     * array of checked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 checked = 4;</code>
     */
    private void clearChecked() {
      checked_ = emptyLongList();
    }

    public static final int UNCHECKED_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.LongList unchecked_;
    /**
     * <pre>
     * array of unchecked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 unchecked = 5;</code>
     */
    public java.util.List<java.lang.Long>
        getUncheckedList() {
      return unchecked_;
    }
    /**
     * <pre>
     * array of unchecked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 unchecked = 5;</code>
     */
    public int getUncheckedCount() {
      return unchecked_.size();
    }
    /**
     * <pre>
     * array of unchecked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 unchecked = 5;</code>
     */
    public long getUnchecked(int index) {
      return unchecked_.getLong(index);
    }
    private void ensureUncheckedIsMutable() {
      if (!unchecked_.isModifiable()) {
        unchecked_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(unchecked_);
       }
    }
    /**
     * <pre>
     * array of unchecked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 unchecked = 5;</code>
     */
    private void setUnchecked(
        int index, long value) {
      ensureUncheckedIsMutable();
      unchecked_.setLong(index, value);
    }
    /**
     * <pre>
     * array of unchecked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 unchecked = 5;</code>
     */
    private void addUnchecked(long value) {
      ensureUncheckedIsMutable();
      unchecked_.addLong(value);
    }
    /**
     * <pre>
     * array of unchecked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 unchecked = 5;</code>
     */
    private void addAllUnchecked(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureUncheckedIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, unchecked_);
    }
    /**
     * <pre>
     * array of unchecked timestamps in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>repeated int64 unchecked = 5;</code>
     */
    private void clearUnchecked() {
      unchecked_ = emptyLongList();
    }

    public static final int IS_CHECKED_FIELD_NUMBER = 6;
    private boolean isChecked_;
    /**
     * <code>bool is_checked = 6;</code>
     */
    public boolean getIsChecked() {
      return isChecked_;
    }
    /**
     * <code>bool is_checked = 6;</code>
     */
    private void setIsChecked(boolean value) {
      
      isChecked_ = value;
    }
    /**
     * <code>bool is_checked = 6;</code>
     */
    private void clearIsChecked() {
      
      isChecked_ = false;
    }

    public static final int CHECKED_TIME_FIELD_NUMBER = 8;
    private long checkedTime_;
    /**
     * <pre>
     * timestamp in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>int64 checked_time = 8;</code>
     */
    public long getCheckedTime() {
      return checkedTime_;
    }
    /**
     * <pre>
     * timestamp in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>int64 checked_time = 8;</code>
     */
    private void setCheckedTime(long value) {
      
      checkedTime_ = value;
    }
    /**
     * <pre>
     * timestamp in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>int64 checked_time = 8;</code>
     */
    private void clearCheckedTime() {
      
      checkedTime_ = 0L;
    }

    public static final int UNCHECKED_TIME_FIELD_NUMBER = 9;
    private long uncheckedTime_;
    /**
     * <pre>
     * timestamp in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>int64 unchecked_time = 9;</code>
     */
    public long getUncheckedTime() {
      return uncheckedTime_;
    }
    /**
     * <pre>
     * timestamp in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>int64 unchecked_time = 9;</code>
     */
    private void setUncheckedTime(long value) {
      
      uncheckedTime_ = value;
    }
    /**
     * <pre>
     * timestamp in "yyyyMMddHHmmss" format
     * </pre>
     *
     * <code>int64 unchecked_time = 9;</code>
     */
    private void clearUncheckedTime() {
      
      uncheckedTime_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!name_.isEmpty()) {
        output.writeString(2, getName());
      }
      if (!quantity_.isEmpty()) {
        output.writeString(3, getQuantity());
      }
      for (int i = 0; i < checked_.size(); i++) {
        output.writeInt64(4, checked_.getLong(i));
      }
      for (int i = 0; i < unchecked_.size(); i++) {
        output.writeInt64(5, unchecked_.getLong(i));
      }
      if (isChecked_ != false) {
        output.writeBool(6, isChecked_);
      }
      if (checkedTime_ != 0L) {
        output.writeInt64(8, checkedTime_);
      }
      if (uncheckedTime_ != 0L) {
        output.writeInt64(9, uncheckedTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!name_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (!quantity_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getQuantity());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < checked_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(checked_.getLong(i));
        }
        size += dataSize;
        size += 1 * getCheckedList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < unchecked_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(unchecked_.getLong(i));
        }
        size += dataSize;
        size += 1 * getUncheckedList().size();
      }
      if (isChecked_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isChecked_);
      }
      if (checkedTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, checkedTime_);
      }
      if (uncheckedTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, uncheckedTime_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fi.mabrosim.shoppinglist.protobuf.Protos.PbItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code protobuf.PbItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          fi.mabrosim.shoppinglist.protobuf.Protos.PbItem, Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.PbItem)
        fi.mabrosim.shoppinglist.protobuf.Protos.PbItemOrBuilder {
      // Construct using fi.mabrosim.shoppinglist.protobuf.Protos.PbItem.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return instance.getId();
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>string quantity = 3;</code>
       */
      public java.lang.String getQuantity() {
        return instance.getQuantity();
      }
      /**
       * <code>string quantity = 3;</code>
       */
      public com.google.protobuf.ByteString
          getQuantityBytes() {
        return instance.getQuantityBytes();
      }
      /**
       * <code>string quantity = 3;</code>
       */
      public Builder setQuantity(
          java.lang.String value) {
        copyOnWrite();
        instance.setQuantity(value);
        return this;
      }
      /**
       * <code>string quantity = 3;</code>
       */
      public Builder clearQuantity() {
        copyOnWrite();
        instance.clearQuantity();
        return this;
      }
      /**
       * <code>string quantity = 3;</code>
       */
      public Builder setQuantityBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setQuantityBytes(value);
        return this;
      }

      /**
       * <pre>
       * array of checked timestamps in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>repeated int64 checked = 4;</code>
       */
      public java.util.List<java.lang.Long>
          getCheckedList() {
        return java.util.Collections.unmodifiableList(
            instance.getCheckedList());
      }
      /**
       * <pre>
       * array of checked timestamps in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>repeated int64 checked = 4;</code>
       */
      public int getCheckedCount() {
        return instance.getCheckedCount();
      }
      /**
       * <pre>
       * array of checked timestamps in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>repeated int64 checked = 4;</code>
       */
      public long getChecked(int index) {
        return instance.getChecked(index);
      }
      /**
       * <pre>
       * array of checked timestamps in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>repeated int64 checked = 4;</code>
       */
      public Builder setChecked(
          int index, long value) {
        copyOnWrite();
        instance.setChecked(index, value);
        return this;
      }
      /**
       * <pre>
       * array of checked timestamps in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>repeated int64 checked = 4;</code>
       */
      public Builder addChecked(long value) {
        copyOnWrite();
        instance.addChecked(value);
        return this;
      }
      /**
       * <pre>
       * array of checked timestamps in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>repeated int64 checked = 4;</code>
       */
      public Builder addAllChecked(
          java.lang.Iterable<? extends java.lang.Long> values) {
        copyOnWrite();
        instance.addAllChecked(values);
        return this;
      }
      /**
       * <pre>
       * array of checked timestamps in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>repeated int64 checked = 4;</code>
       */
      public Builder clearChecked() {
        copyOnWrite();
        instance.clearChecked();
        return this;
      }

      /**
       * <pre>
       * array of unchecked timestamps in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>repeated int64 unchecked = 5;</code>
       */
      public java.util.List<java.lang.Long>
          getUncheckedList() {
        return java.util.Collections.unmodifiableList(
            instance.getUncheckedList());
      }
      /**
       * <pre>
       * array of unchecked timestamps in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>repeated int64 unchecked = 5;</code>
       */
      public int getUncheckedCount() {
        return instance.getUncheckedCount();
      }
      /**
       * <pre>
       * array of unchecked timestamps in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>repeated int64 unchecked = 5;</code>
       */
      public long getUnchecked(int index) {
        return instance.getUnchecked(index);
      }
      /**
       * <pre>
       * array of unchecked timestamps in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>repeated int64 unchecked = 5;</code>
       */
      public Builder setUnchecked(
          int index, long value) {
        copyOnWrite();
        instance.setUnchecked(index, value);
        return this;
      }
      /**
       * <pre>
       * array of unchecked timestamps in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>repeated int64 unchecked = 5;</code>
       */
      public Builder addUnchecked(long value) {
        copyOnWrite();
        instance.addUnchecked(value);
        return this;
      }
      /**
       * <pre>
       * array of unchecked timestamps in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>repeated int64 unchecked = 5;</code>
       */
      public Builder addAllUnchecked(
          java.lang.Iterable<? extends java.lang.Long> values) {
        copyOnWrite();
        instance.addAllUnchecked(values);
        return this;
      }
      /**
       * <pre>
       * array of unchecked timestamps in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>repeated int64 unchecked = 5;</code>
       */
      public Builder clearUnchecked() {
        copyOnWrite();
        instance.clearUnchecked();
        return this;
      }

      /**
       * <code>bool is_checked = 6;</code>
       */
      public boolean getIsChecked() {
        return instance.getIsChecked();
      }
      /**
       * <code>bool is_checked = 6;</code>
       */
      public Builder setIsChecked(boolean value) {
        copyOnWrite();
        instance.setIsChecked(value);
        return this;
      }
      /**
       * <code>bool is_checked = 6;</code>
       */
      public Builder clearIsChecked() {
        copyOnWrite();
        instance.clearIsChecked();
        return this;
      }

      /**
       * <pre>
       * timestamp in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>int64 checked_time = 8;</code>
       */
      public long getCheckedTime() {
        return instance.getCheckedTime();
      }
      /**
       * <pre>
       * timestamp in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>int64 checked_time = 8;</code>
       */
      public Builder setCheckedTime(long value) {
        copyOnWrite();
        instance.setCheckedTime(value);
        return this;
      }
      /**
       * <pre>
       * timestamp in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>int64 checked_time = 8;</code>
       */
      public Builder clearCheckedTime() {
        copyOnWrite();
        instance.clearCheckedTime();
        return this;
      }

      /**
       * <pre>
       * timestamp in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>int64 unchecked_time = 9;</code>
       */
      public long getUncheckedTime() {
        return instance.getUncheckedTime();
      }
      /**
       * <pre>
       * timestamp in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>int64 unchecked_time = 9;</code>
       */
      public Builder setUncheckedTime(long value) {
        copyOnWrite();
        instance.setUncheckedTime(value);
        return this;
      }
      /**
       * <pre>
       * timestamp in "yyyyMMddHHmmss" format
       * </pre>
       *
       * <code>int64 unchecked_time = 9;</code>
       */
      public Builder clearUncheckedTime() {
        copyOnWrite();
        instance.clearUncheckedTime();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.PbItem)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new fi.mabrosim.shoppinglist.protobuf.Protos.PbItem();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          checked_.makeImmutable();
          unchecked_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          fi.mabrosim.shoppinglist.protobuf.Protos.PbItem other = (fi.mabrosim.shoppinglist.protobuf.Protos.PbItem) arg1;
          id_ = visitor.visitLong(id_ != 0L, id_,
              other.id_ != 0L, other.id_);
          name_ = visitor.visitString(!name_.isEmpty(), name_,
              !other.name_.isEmpty(), other.name_);
          quantity_ = visitor.visitString(!quantity_.isEmpty(), quantity_,
              !other.quantity_.isEmpty(), other.quantity_);
          checked_= visitor.visitLongList(checked_, other.checked_);
          unchecked_= visitor.visitLongList(unchecked_, other.unchecked_);
          isChecked_ = visitor.visitBoolean(isChecked_ != false, isChecked_,
              other.isChecked_ != false, other.isChecked_);
          checkedTime_ = visitor.visitLong(checkedTime_ != 0L, checkedTime_,
              other.checkedTime_ != 0L, other.checkedTime_);
          uncheckedTime_ = visitor.visitLong(uncheckedTime_ != 0L, uncheckedTime_,
              other.uncheckedTime_ != 0L, other.uncheckedTime_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  id_ = input.readInt64();
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  quantity_ = s;
                  break;
                }
                case 32: {
                  if (!checked_.isModifiable()) {
                    checked_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(checked_);
                  }
                  checked_.addLong(input.readInt64());
                  break;
                }
                case 34: {
                  int length = input.readRawVarint32();
                  int limit = input.pushLimit(length);
                  if (!checked_.isModifiable() && input.getBytesUntilLimit() > 0) {
                    checked_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(checked_);
                  }
                  while (input.getBytesUntilLimit() > 0) {
                    checked_.addLong(input.readInt64());
                  }
                  input.popLimit(limit);
                  break;
                }
                case 40: {
                  if (!unchecked_.isModifiable()) {
                    unchecked_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(unchecked_);
                  }
                  unchecked_.addLong(input.readInt64());
                  break;
                }
                case 42: {
                  int length = input.readRawVarint32();
                  int limit = input.pushLimit(length);
                  if (!unchecked_.isModifiable() && input.getBytesUntilLimit() > 0) {
                    unchecked_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(unchecked_);
                  }
                  while (input.getBytesUntilLimit() > 0) {
                    unchecked_.addLong(input.readInt64());
                  }
                  input.popLimit(limit);
                  break;
                }
                case 48: {

                  isChecked_ = input.readBool();
                  break;
                }
                case 64: {

                  checkedTime_ = input.readInt64();
                  break;
                }
                case 72: {

                  uncheckedTime_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (fi.mabrosim.shoppinglist.protobuf.Protos.PbItem.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:protobuf.PbItem)
    private static final fi.mabrosim.shoppinglist.protobuf.Protos.PbItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PbItem();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PbItem> PARSER;

    public static com.google.protobuf.Parser<PbItem> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PbLabelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.PbLabel)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    java.util.List<fi.mabrosim.shoppinglist.protobuf.Protos.PbItem> 
        getItemList();
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    fi.mabrosim.shoppinglist.protobuf.Protos.PbItem getItem(int index);
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    int getItemCount();
  }
  /**
   * Protobuf type {@code protobuf.PbLabel}
   */
  public  static final class PbLabel extends
      com.google.protobuf.GeneratedMessageLite<
          PbLabel, PbLabel.Builder> implements
      // @@protoc_insertion_point(message_implements:protobuf.PbLabel)
      PbLabelOrBuilder {
    private PbLabel() {
      name_ = "";
      item_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    private void setId(long value) {
      
      id_ = value;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    private void clearId() {
      
      id_ = 0L;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.String name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 2;</code>
     */
    private void setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
    }
    /**
     * <code>string name = 2;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 2;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value.toStringUtf8();
    }

    public static final int ITEM_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<fi.mabrosim.shoppinglist.protobuf.Protos.PbItem> item_;
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    public java.util.List<fi.mabrosim.shoppinglist.protobuf.Protos.PbItem> getItemList() {
      return item_;
    }
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    public java.util.List<? extends fi.mabrosim.shoppinglist.protobuf.Protos.PbItemOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    public fi.mabrosim.shoppinglist.protobuf.Protos.PbItem getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    public fi.mabrosim.shoppinglist.protobuf.Protos.PbItemOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }
    private void ensureItemIsMutable() {
      if (!item_.isModifiable()) {
        item_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(item_);
       }
    }

    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    private void setItem(
        int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbItem value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.set(index, value);
    }
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    private void setItem(
        int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbItem.Builder builderForValue) {
      ensureItemIsMutable();
      item_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    private void addItem(fi.mabrosim.shoppinglist.protobuf.Protos.PbItem value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.add(value);
    }
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    private void addItem(
        int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbItem value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.add(index, value);
    }
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    private void addItem(
        fi.mabrosim.shoppinglist.protobuf.Protos.PbItem.Builder builderForValue) {
      ensureItemIsMutable();
      item_.add(builderForValue.build());
    }
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    private void addItem(
        int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbItem.Builder builderForValue) {
      ensureItemIsMutable();
      item_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    private void addAllItem(
        java.lang.Iterable<? extends fi.mabrosim.shoppinglist.protobuf.Protos.PbItem> values) {
      ensureItemIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, item_);
    }
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    private void clearItem() {
      item_ = emptyProtobufList();
    }
    /**
     * <code>repeated .protobuf.PbItem item = 3;</code>
     */
    private void removeItem(int index) {
      ensureItemIsMutable();
      item_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!name_.isEmpty()) {
        output.writeString(2, getName());
      }
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(3, item_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!name_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, item_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code protobuf.PbLabel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel, Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.PbLabel)
        fi.mabrosim.shoppinglist.protobuf.Protos.PbLabelOrBuilder {
      // Construct using fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return instance.getId();
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>repeated .protobuf.PbItem item = 3;</code>
       */
      public java.util.List<fi.mabrosim.shoppinglist.protobuf.Protos.PbItem> getItemList() {
        return java.util.Collections.unmodifiableList(
            instance.getItemList());
      }
      /**
       * <code>repeated .protobuf.PbItem item = 3;</code>
       */
      public int getItemCount() {
        return instance.getItemCount();
      }/**
       * <code>repeated .protobuf.PbItem item = 3;</code>
       */
      public fi.mabrosim.shoppinglist.protobuf.Protos.PbItem getItem(int index) {
        return instance.getItem(index);
      }
      /**
       * <code>repeated .protobuf.PbItem item = 3;</code>
       */
      public Builder setItem(
          int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbItem value) {
        copyOnWrite();
        instance.setItem(index, value);
        return this;
      }
      /**
       * <code>repeated .protobuf.PbItem item = 3;</code>
       */
      public Builder setItem(
          int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbItem.Builder builderForValue) {
        copyOnWrite();
        instance.setItem(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .protobuf.PbItem item = 3;</code>
       */
      public Builder addItem(fi.mabrosim.shoppinglist.protobuf.Protos.PbItem value) {
        copyOnWrite();
        instance.addItem(value);
        return this;
      }
      /**
       * <code>repeated .protobuf.PbItem item = 3;</code>
       */
      public Builder addItem(
          int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbItem value) {
        copyOnWrite();
        instance.addItem(index, value);
        return this;
      }
      /**
       * <code>repeated .protobuf.PbItem item = 3;</code>
       */
      public Builder addItem(
          fi.mabrosim.shoppinglist.protobuf.Protos.PbItem.Builder builderForValue) {
        copyOnWrite();
        instance.addItem(builderForValue);
        return this;
      }
      /**
       * <code>repeated .protobuf.PbItem item = 3;</code>
       */
      public Builder addItem(
          int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbItem.Builder builderForValue) {
        copyOnWrite();
        instance.addItem(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .protobuf.PbItem item = 3;</code>
       */
      public Builder addAllItem(
          java.lang.Iterable<? extends fi.mabrosim.shoppinglist.protobuf.Protos.PbItem> values) {
        copyOnWrite();
        instance.addAllItem(values);
        return this;
      }
      /**
       * <code>repeated .protobuf.PbItem item = 3;</code>
       */
      public Builder clearItem() {
        copyOnWrite();
        instance.clearItem();
        return this;
      }
      /**
       * <code>repeated .protobuf.PbItem item = 3;</code>
       */
      public Builder removeItem(int index) {
        copyOnWrite();
        instance.removeItem(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.PbLabel)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          item_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel other = (fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel) arg1;
          id_ = visitor.visitLong(id_ != 0L, id_,
              other.id_ != 0L, other.id_);
          name_ = visitor.visitString(!name_.isEmpty(), name_,
              !other.name_.isEmpty(), other.name_);
          item_= visitor.visitList(item_, other.item_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  id_ = input.readInt64();
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
                case 26: {
                  if (!item_.isModifiable()) {
                    item_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(item_);
                  }
                  item_.add(
                      input.readMessage(fi.mabrosim.shoppinglist.protobuf.Protos.PbItem.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:protobuf.PbLabel)
    private static final fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PbLabel();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PbLabel> PARSER;

    public static com.google.protobuf.Parser<PbLabel> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PbItemListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.PbItemList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    java.util.List<fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel> 
        getLabelList();
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel getLabel(int index);
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    int getLabelCount();
  }
  /**
   * Protobuf type {@code protobuf.PbItemList}
   */
  public  static final class PbItemList extends
      com.google.protobuf.GeneratedMessageLite<
          PbItemList, PbItemList.Builder> implements
      // @@protoc_insertion_point(message_implements:protobuf.PbItemList)
      PbItemListOrBuilder {
    private PbItemList() {
      name_ = "";
      label_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    private void setId(long value) {
      
      id_ = value;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    private void clearId() {
      
      id_ = 0L;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.String name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 2;</code>
     */
    private void setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
    }
    /**
     * <code>string name = 2;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 2;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value.toStringUtf8();
    }

    public static final int LABEL_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel> label_;
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    public java.util.List<fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel> getLabelList() {
      return label_;
    }
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    public java.util.List<? extends fi.mabrosim.shoppinglist.protobuf.Protos.PbLabelOrBuilder> 
        getLabelOrBuilderList() {
      return label_;
    }
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    public int getLabelCount() {
      return label_.size();
    }
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    public fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel getLabel(int index) {
      return label_.get(index);
    }
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    public fi.mabrosim.shoppinglist.protobuf.Protos.PbLabelOrBuilder getLabelOrBuilder(
        int index) {
      return label_.get(index);
    }
    private void ensureLabelIsMutable() {
      if (!label_.isModifiable()) {
        label_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(label_);
       }
    }

    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    private void setLabel(
        int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureLabelIsMutable();
      label_.set(index, value);
    }
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    private void setLabel(
        int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel.Builder builderForValue) {
      ensureLabelIsMutable();
      label_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    private void addLabel(fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureLabelIsMutable();
      label_.add(value);
    }
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    private void addLabel(
        int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureLabelIsMutable();
      label_.add(index, value);
    }
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    private void addLabel(
        fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel.Builder builderForValue) {
      ensureLabelIsMutable();
      label_.add(builderForValue.build());
    }
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    private void addLabel(
        int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel.Builder builderForValue) {
      ensureLabelIsMutable();
      label_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    private void addAllLabel(
        java.lang.Iterable<? extends fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel> values) {
      ensureLabelIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, label_);
    }
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    private void clearLabel() {
      label_ = emptyProtobufList();
    }
    /**
     * <code>repeated .protobuf.PbLabel label = 3;</code>
     */
    private void removeLabel(int index) {
      ensureLabelIsMutable();
      label_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!name_.isEmpty()) {
        output.writeString(2, getName());
      }
      for (int i = 0; i < label_.size(); i++) {
        output.writeMessage(3, label_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!name_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      for (int i = 0; i < label_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, label_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code protobuf.PbItemList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList, Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.PbItemList)
        fi.mabrosim.shoppinglist.protobuf.Protos.PbItemListOrBuilder {
      // Construct using fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return instance.getId();
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>repeated .protobuf.PbLabel label = 3;</code>
       */
      public java.util.List<fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel> getLabelList() {
        return java.util.Collections.unmodifiableList(
            instance.getLabelList());
      }
      /**
       * <code>repeated .protobuf.PbLabel label = 3;</code>
       */
      public int getLabelCount() {
        return instance.getLabelCount();
      }/**
       * <code>repeated .protobuf.PbLabel label = 3;</code>
       */
      public fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel getLabel(int index) {
        return instance.getLabel(index);
      }
      /**
       * <code>repeated .protobuf.PbLabel label = 3;</code>
       */
      public Builder setLabel(
          int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel value) {
        copyOnWrite();
        instance.setLabel(index, value);
        return this;
      }
      /**
       * <code>repeated .protobuf.PbLabel label = 3;</code>
       */
      public Builder setLabel(
          int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel.Builder builderForValue) {
        copyOnWrite();
        instance.setLabel(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .protobuf.PbLabel label = 3;</code>
       */
      public Builder addLabel(fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel value) {
        copyOnWrite();
        instance.addLabel(value);
        return this;
      }
      /**
       * <code>repeated .protobuf.PbLabel label = 3;</code>
       */
      public Builder addLabel(
          int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel value) {
        copyOnWrite();
        instance.addLabel(index, value);
        return this;
      }
      /**
       * <code>repeated .protobuf.PbLabel label = 3;</code>
       */
      public Builder addLabel(
          fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel.Builder builderForValue) {
        copyOnWrite();
        instance.addLabel(builderForValue);
        return this;
      }
      /**
       * <code>repeated .protobuf.PbLabel label = 3;</code>
       */
      public Builder addLabel(
          int index, fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel.Builder builderForValue) {
        copyOnWrite();
        instance.addLabel(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .protobuf.PbLabel label = 3;</code>
       */
      public Builder addAllLabel(
          java.lang.Iterable<? extends fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel> values) {
        copyOnWrite();
        instance.addAllLabel(values);
        return this;
      }
      /**
       * <code>repeated .protobuf.PbLabel label = 3;</code>
       */
      public Builder clearLabel() {
        copyOnWrite();
        instance.clearLabel();
        return this;
      }
      /**
       * <code>repeated .protobuf.PbLabel label = 3;</code>
       */
      public Builder removeLabel(int index) {
        copyOnWrite();
        instance.removeLabel(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.PbItemList)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          label_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList other = (fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList) arg1;
          id_ = visitor.visitLong(id_ != 0L, id_,
              other.id_ != 0L, other.id_);
          name_ = visitor.visitString(!name_.isEmpty(), name_,
              !other.name_.isEmpty(), other.name_);
          label_= visitor.visitList(label_, other.label_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  id_ = input.readInt64();
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
                case 26: {
                  if (!label_.isModifiable()) {
                    label_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(label_);
                  }
                  label_.add(
                      input.readMessage(fi.mabrosim.shoppinglist.protobuf.Protos.PbLabel.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:protobuf.PbItemList)
    private static final fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PbItemList();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static fi.mabrosim.shoppinglist.protobuf.Protos.PbItemList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PbItemList> PARSER;

    public static com.google.protobuf.Parser<PbItemList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
